### ISSUE TITLE
ConfigMap Key Conflict When Multiple RoleBinding Map to the Same Built-in Role

### ISSUE THREAD

**Issue by pkbhowmick** [argoproj-labs/argocd-rbac-operator#41]
**Description**
When multiple ArgoCDRoleBinding resources from different namespaces refer to roles that map to the same built-in Argo CD role (e.g. admin), the RBAC operator generates duplicate ConfigMap keys, which causes the last-applied binding to overwrite the previous ones in the generated argocd-rbac-cm.

**To Reproduce**

1. Create two namespaces:

```
kubectl create namespace dev-a
kubectl create namespace dev-b
```

2. Create two ArgoCDRoleBinding resources, each binding a different user/group to a role that maps to admin.

```
# dev-a-rolebinding.yaml
apiVersion: rbac-operator.argoproj-labs.io/v1alpha1
kind: ArgoCDRoleBinding
metadata:
  name: dev-a-binding
  namespace: dev-a
spec:
  subjects:
    - kind: sso
      name: dev-a-admin
  argocdRoleRef:
    name: admin
```
```
# dev-b-rolebinding.yaml
apiVersion: rbac-operator.argoproj-labs.io/v1alpha1
kind: ArgoCDRoleBinding
metadata:
  name: dev-b-binding
  namespace: dev-b
spec:
  subjects:
    - kind: sso
      name: dev-b-admin
  argocdRoleRef:
    name: admin
```
Apply both bindings:
```
kubectl apply -f dev-a-rolebinding.yaml
kubectl apply -f dev-b-rolebinding.yaml
```
Inspect the generated argocd-rbac-cm ConfigMap:

```
kubectl -n <argocd-namespace> get configmap argocd-rbac-cm -o yaml
```
Observed Behavior:
The RBAC operator only includes the second binding:

```
data:
  policy.csv: |
    g, dev-b-admin, role:admin
```
➡️ The first binding (from dev-a) is missing, having been overwritten due to the key conflict.

**Expected behavior**
- All ArgoCDRoleBinding entries should be preserved, even if they point to the same built-in role.
- The generated key in the ConfigMap should be unique (e.g., include namespace/rolebinding context).

🛠 Proposed Fix: Use RoleBinding-Specific Key
Update the operator logic to generate unique ConfigMap keys per ArgoCDRoleBinding, instead of relying solely on the target Argo CD namespace and role name.

🔁 Suggested Format:
```
policy.<binding-namespace>.<rolebinding-name>.csv
```

Example:
```
policy.dev-a.dev-a-binding.csv: |
  g, dev-a-admin, role:admin

policy.dev-b.dev-b-binding.csv: |
  g, dev-b-admin, role:admin
```
